### ISSUE TITLE
Code working?

### ISSUE THREAD

**Issue by sskumars** [beaubellamy/BikeSales#4]
Hey,
I came across your code when I was looking for a way to scrape bike sales data to run some analysis. Was wondering if it is still working on your end? I am not able to get it to work.
Cheers

**Comment by beaubellamy** [comment]
Sorry for the late reply, I ended up getting blocked, and didn't spend much time trying to get it to work. I notice they have changed the website since the original code. 
I've started looking at trying to get it working again.
